// auto generated by generate_cpu_attn_dispatch.py
// clang-format off

#ifndef CPU_ATTN_DISPATCH_GENERATED_H
#define CPU_ATTN_DISPATCH_GENERATED_H

#include "cpu_attn_vec.hpp"
#include "cpu_attn_vec16.hpp"

#ifdef CPU_CAPABILITY_AMXBF16
  #include "cpu_attn_amx.hpp"
#endif

#ifdef __aarch64__
  #include "cpu_attn_neon.hpp"
#endif


inline int64_t encode_cpu_attn_params(int64_t head_dim, cpu_attention::ISA isa) {
  return (head_dim << 8) | static_cast<int64_t>(isa);
}

// Dispatch macro using encoded parameters
#if defined(CPU_CAPABILITY_AMXBF16)
#define CPU_ATTN_DISPATCH(HEAD_DIM, ISA_TYPE, ...) \
  [&] { \
    int64_t encoded_params = encode_cpu_attn_params(HEAD_DIM, ISA_TYPE); \
    switch (encoded_params) { \
      case 8192LL: { /* head_dim=32, isa=AMX */ \
        constexpr size_t head_dim = 32; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::AMX, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 8193LL: { /* head_dim=32, isa=VEC */ \
        constexpr size_t head_dim = 32; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 8194LL: { /* head_dim=32, isa=VEC16 */ \
        constexpr size_t head_dim = 32; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 16384LL: { /* head_dim=64, isa=AMX */ \
        constexpr size_t head_dim = 64; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::AMX, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 16385LL: { /* head_dim=64, isa=VEC */ \
        constexpr size_t head_dim = 64; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 16386LL: { /* head_dim=64, isa=VEC16 */ \
        constexpr size_t head_dim = 64; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 24576LL: { /* head_dim=96, isa=AMX */ \
        constexpr size_t head_dim = 96; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::AMX, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 24577LL: { /* head_dim=96, isa=VEC */ \
        constexpr size_t head_dim = 96; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 24578LL: { /* head_dim=96, isa=VEC16 */ \
        constexpr size_t head_dim = 96; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 32768LL: { /* head_dim=128, isa=AMX */ \
        constexpr size_t head_dim = 128; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::AMX, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 32769LL: { /* head_dim=128, isa=VEC */ \
        constexpr size_t head_dim = 128; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 32770LL: { /* head_dim=128, isa=VEC16 */ \
        constexpr size_t head_dim = 128; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 40960LL: { /* head_dim=160, isa=AMX */ \
        constexpr size_t head_dim = 160; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::AMX, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 40961LL: { /* head_dim=160, isa=VEC */ \
        constexpr size_t head_dim = 160; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 40962LL: { /* head_dim=160, isa=VEC16 */ \
        constexpr size_t head_dim = 160; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 49152LL: { /* head_dim=192, isa=AMX */ \
        constexpr size_t head_dim = 192; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::AMX, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 49153LL: { /* head_dim=192, isa=VEC */ \
        constexpr size_t head_dim = 192; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 49154LL: { /* head_dim=192, isa=VEC16 */ \
        constexpr size_t head_dim = 192; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 57344LL: { /* head_dim=224, isa=AMX */ \
        constexpr size_t head_dim = 224; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::AMX, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 57345LL: { /* head_dim=224, isa=VEC */ \
        constexpr size_t head_dim = 224; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 57346LL: { /* head_dim=224, isa=VEC16 */ \
        constexpr size_t head_dim = 224; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 65536LL: { /* head_dim=256, isa=AMX */ \
        constexpr size_t head_dim = 256; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::AMX, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 65537LL: { /* head_dim=256, isa=VEC */ \
        constexpr size_t head_dim = 256; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 65538LL: { /* head_dim=256, isa=VEC16 */ \
        constexpr size_t head_dim = 256; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 20480LL: { /* head_dim=80, isa=AMX (using VEC16) */ \
        constexpr size_t head_dim = 80; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 20481LL: { /* head_dim=80, isa=VEC (using VEC16) */ \
        constexpr size_t head_dim = 80; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 20482LL: { /* head_dim=80, isa=VEC16 (using VEC16) */ \
        constexpr size_t head_dim = 80; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 28672LL: { /* head_dim=112, isa=AMX (using VEC16) */ \
        constexpr size_t head_dim = 112; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 28673LL: { /* head_dim=112, isa=VEC (using VEC16) */ \
        constexpr size_t head_dim = 112; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 28674LL: { /* head_dim=112, isa=VEC16 (using VEC16) */ \
        constexpr size_t head_dim = 112; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      default: { \
        TORCH_CHECK(false, "Unsupported CPU attention configuration: head_dim=" + \
                    std::to_string(HEAD_DIM) + " isa=" + \
                    std::to_string(static_cast<int>(ISA_TYPE))); \
      } \
    } \
  }()

#elif defined(__aarch64__)
#define CPU_ATTN_DISPATCH(HEAD_DIM, ISA_TYPE, ...) \
  [&] { \
    int64_t encoded_params = encode_cpu_attn_params(HEAD_DIM, ISA_TYPE); \
    switch (encoded_params) { \
      case 8195LL: { /* head_dim=32, isa=NEON */ \
        constexpr size_t head_dim = 32; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::NEON, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 8193LL: { /* head_dim=32, isa=VEC */ \
        constexpr size_t head_dim = 32; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 8194LL: { /* head_dim=32, isa=VEC16 */ \
        constexpr size_t head_dim = 32; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 16387LL: { /* head_dim=64, isa=NEON */ \
        constexpr size_t head_dim = 64; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::NEON, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 16385LL: { /* head_dim=64, isa=VEC */ \
        constexpr size_t head_dim = 64; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 16386LL: { /* head_dim=64, isa=VEC16 */ \
        constexpr size_t head_dim = 64; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 24579LL: { /* head_dim=96, isa=NEON */ \
        constexpr size_t head_dim = 96; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::NEON, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 24577LL: { /* head_dim=96, isa=VEC */ \
        constexpr size_t head_dim = 96; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 24578LL: { /* head_dim=96, isa=VEC16 */ \
        constexpr size_t head_dim = 96; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 32771LL: { /* head_dim=128, isa=NEON */ \
        constexpr size_t head_dim = 128; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::NEON, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 32769LL: { /* head_dim=128, isa=VEC */ \
        constexpr size_t head_dim = 128; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 32770LL: { /* head_dim=128, isa=VEC16 */ \
        constexpr size_t head_dim = 128; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 40963LL: { /* head_dim=160, isa=NEON */ \
        constexpr size_t head_dim = 160; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::NEON, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 40961LL: { /* head_dim=160, isa=VEC */ \
        constexpr size_t head_dim = 160; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 40962LL: { /* head_dim=160, isa=VEC16 */ \
        constexpr size_t head_dim = 160; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 49155LL: { /* head_dim=192, isa=NEON */ \
        constexpr size_t head_dim = 192; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::NEON, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 49153LL: { /* head_dim=192, isa=VEC */ \
        constexpr size_t head_dim = 192; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 49154LL: { /* head_dim=192, isa=VEC16 */ \
        constexpr size_t head_dim = 192; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 57347LL: { /* head_dim=224, isa=NEON */ \
        constexpr size_t head_dim = 224; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::NEON, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 57345LL: { /* head_dim=224, isa=VEC */ \
        constexpr size_t head_dim = 224; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 57346LL: { /* head_dim=224, isa=VEC16 */ \
        constexpr size_t head_dim = 224; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 65539LL: { /* head_dim=256, isa=NEON */ \
        constexpr size_t head_dim = 256; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::NEON, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 65537LL: { /* head_dim=256, isa=VEC */ \
        constexpr size_t head_dim = 256; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 65538LL: { /* head_dim=256, isa=VEC16 */ \
        constexpr size_t head_dim = 256; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 20483LL: { /* head_dim=80, isa=NEON (using VEC16) */ \
        constexpr size_t head_dim = 80; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 20481LL: { /* head_dim=80, isa=VEC (using VEC16) */ \
        constexpr size_t head_dim = 80; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 20482LL: { /* head_dim=80, isa=VEC16 (using VEC16) */ \
        constexpr size_t head_dim = 80; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 28675LL: { /* head_dim=112, isa=NEON (using VEC16) */ \
        constexpr size_t head_dim = 112; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 28673LL: { /* head_dim=112, isa=VEC (using VEC16) */ \
        constexpr size_t head_dim = 112; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 28674LL: { /* head_dim=112, isa=VEC16 (using VEC16) */ \
        constexpr size_t head_dim = 112; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      default: { \
        TORCH_CHECK(false, "Unsupported CPU attention configuration: head_dim=" + \
                    std::to_string(HEAD_DIM) + " isa=" + \
                    std::to_string(static_cast<int>(ISA_TYPE))); \
      } \
    } \
  }()

#else
#define CPU_ATTN_DISPATCH(HEAD_DIM, ISA_TYPE, ...) \
  [&] { \
    int64_t encoded_params = encode_cpu_attn_params(HEAD_DIM, ISA_TYPE); \
    switch (encoded_params) { \
      case 8193LL: { /* head_dim=32, isa=VEC */ \
        constexpr size_t head_dim = 32; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 8194LL: { /* head_dim=32, isa=VEC16 */ \
        constexpr size_t head_dim = 32; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 16385LL: { /* head_dim=64, isa=VEC */ \
        constexpr size_t head_dim = 64; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 16386LL: { /* head_dim=64, isa=VEC16 */ \
        constexpr size_t head_dim = 64; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 24577LL: { /* head_dim=96, isa=VEC */ \
        constexpr size_t head_dim = 96; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 24578LL: { /* head_dim=96, isa=VEC16 */ \
        constexpr size_t head_dim = 96; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 32769LL: { /* head_dim=128, isa=VEC */ \
        constexpr size_t head_dim = 128; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 32770LL: { /* head_dim=128, isa=VEC16 */ \
        constexpr size_t head_dim = 128; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 40961LL: { /* head_dim=160, isa=VEC */ \
        constexpr size_t head_dim = 160; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 40962LL: { /* head_dim=160, isa=VEC16 */ \
        constexpr size_t head_dim = 160; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 49153LL: { /* head_dim=192, isa=VEC */ \
        constexpr size_t head_dim = 192; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 49154LL: { /* head_dim=192, isa=VEC16 */ \
        constexpr size_t head_dim = 192; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 57345LL: { /* head_dim=224, isa=VEC */ \
        constexpr size_t head_dim = 224; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 57346LL: { /* head_dim=224, isa=VEC16 */ \
        constexpr size_t head_dim = 224; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 65537LL: { /* head_dim=256, isa=VEC */ \
        constexpr size_t head_dim = 256; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 65538LL: { /* head_dim=256, isa=VEC16 */ \
        constexpr size_t head_dim = 256; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 20481LL: { /* head_dim=80, isa=VEC (using VEC16) */ \
        constexpr size_t head_dim = 80; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 20482LL: { /* head_dim=80, isa=VEC16 (using VEC16) */ \
        constexpr size_t head_dim = 80; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 28673LL: { /* head_dim=112, isa=VEC (using VEC16) */ \
        constexpr size_t head_dim = 112; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      case 28674LL: { /* head_dim=112, isa=VEC16 (using VEC16) */ \
        constexpr size_t head_dim = 112; \
        using attn_impl = cpu_attention::AttentionImpl<cpu_attention::ISA::VEC16, \
                                                       scalar_t, head_dim>; \
        return __VA_ARGS__(); \
      } \
      default: { \
        TORCH_CHECK(false, "Unsupported CPU attention configuration: head_dim=" + \
                    std::to_string(HEAD_DIM) + " isa=" + \
                    std::to_string(static_cast<int>(ISA_TYPE))); \
      } \
    } \
  }()

#endif  /* CPU_CAPABILITY_AMXBF16 / __aarch64__ */

#endif  // CPU_ATTN_DISPATCH_GENERATED_H
